// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckBalanceRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckBalanceRequest) Reset()         { *m = CheckBalanceRequest{} }
func (m *CheckBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*CheckBalanceRequest) ProtoMessage()    {}
func (*CheckBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *CheckBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckBalanceRequest.Unmarshal(m, b)
}
func (m *CheckBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckBalanceRequest.Marshal(b, m, deterministic)
}
func (m *CheckBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckBalanceRequest.Merge(m, src)
}
func (m *CheckBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_CheckBalanceRequest.Size(m)
}
func (m *CheckBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckBalanceRequest proto.InternalMessageInfo

func (m *CheckBalanceRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type CheckBalanceResponse struct {
	Reply                string   `protobuf:"bytes,1,opt,name=Reply,proto3" json:"Reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckBalanceResponse) Reset()         { *m = CheckBalanceResponse{} }
func (m *CheckBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*CheckBalanceResponse) ProtoMessage()    {}
func (*CheckBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *CheckBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckBalanceResponse.Unmarshal(m, b)
}
func (m *CheckBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckBalanceResponse.Marshal(b, m, deterministic)
}
func (m *CheckBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckBalanceResponse.Merge(m, src)
}
func (m *CheckBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_CheckBalanceResponse.Size(m)
}
func (m *CheckBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckBalanceResponse proto.InternalMessageInfo

func (m *CheckBalanceResponse) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

type ReductionRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReductionRequest) Reset()         { *m = ReductionRequest{} }
func (m *ReductionRequest) String() string { return proto.CompactTextString(m) }
func (*ReductionRequest) ProtoMessage()    {}
func (*ReductionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *ReductionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReductionRequest.Unmarshal(m, b)
}
func (m *ReductionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReductionRequest.Marshal(b, m, deterministic)
}
func (m *ReductionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReductionRequest.Merge(m, src)
}
func (m *ReductionRequest) XXX_Size() int {
	return xxx_messageInfo_ReductionRequest.Size(m)
}
func (m *ReductionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReductionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReductionRequest proto.InternalMessageInfo

func (m *ReductionRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ReductionRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ReductionResponse struct {
	Reply                string   `protobuf:"bytes,1,opt,name=Reply,proto3" json:"Reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReductionResponse) Reset()         { *m = ReductionResponse{} }
func (m *ReductionResponse) String() string { return proto.CompactTextString(m) }
func (*ReductionResponse) ProtoMessage()    {}
func (*ReductionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *ReductionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReductionResponse.Unmarshal(m, b)
}
func (m *ReductionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReductionResponse.Marshal(b, m, deterministic)
}
func (m *ReductionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReductionResponse.Merge(m, src)
}
func (m *ReductionResponse) XXX_Size() int {
	return xxx_messageInfo_ReductionResponse.Size(m)
}
func (m *ReductionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReductionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReductionResponse proto.InternalMessageInfo

func (m *ReductionResponse) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckBalanceRequest)(nil), "main.CheckBalanceRequest")
	proto.RegisterType((*CheckBalanceResponse)(nil), "main.CheckBalanceResponse")
	proto.RegisterType((*ReductionRequest)(nil), "main.ReductionRequest")
	proto.RegisterType((*ReductionResponse)(nil), "main.ReductionResponse")
}

func init() {
	proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0)
}

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53,
	0xd2, 0xe7, 0x12, 0x76, 0xce, 0x48, 0x4d, 0xce, 0x76, 0x4a, 0xcc, 0x49, 0xcc, 0x4b, 0x4e, 0x0d,
	0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe0, 0x62, 0x77, 0x84, 0xa8, 0x96, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x95, 0x74, 0xb8, 0x44, 0x50, 0x35, 0x14, 0x17, 0xe4, 0xe7,
	0x15, 0xa7, 0x0a, 0x89, 0x70, 0xb1, 0x06, 0xa5, 0x16, 0xe4, 0x54, 0x42, 0xd5, 0x43, 0x38, 0x4a,
	0x2e, 0x5c, 0x02, 0x41, 0xa9, 0x29, 0xa5, 0xc9, 0x25, 0x99, 0xf9, 0x79, 0x04, 0xcd, 0x16, 0x12,
	0xe3, 0x62, 0x73, 0xcc, 0x05, 0x4b, 0x30, 0x29, 0x30, 0x6a, 0x30, 0x06, 0x41, 0x79, 0x4a, 0x9a,
	0x5c, 0x82, 0x48, 0xa6, 0xe0, 0xb3, 0xd0, 0x68, 0x12, 0x23, 0xdc, 0x74, 0x21, 0x77, 0x2e, 0x1e,
	0x64, 0xa7, 0x0a, 0x49, 0xea, 0x81, 0xbc, 0xac, 0x87, 0xc5, 0xbf, 0x52, 0x52, 0xd8, 0xa4, 0x20,
	0x16, 0x29, 0x31, 0x08, 0xd9, 0x71, 0x71, 0xc2, 0xed, 0x17, 0x12, 0x83, 0x28, 0x45, 0xf7, 0x96,
	0x94, 0x38, 0x86, 0x38, 0x4c, 0x7f, 0x12, 0x1b, 0x38, 0xc4, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xb5, 0x92, 0xff, 0x7c, 0x82, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	CheckBalance(ctx context.Context, in *CheckBalanceRequest, opts ...grpc.CallOption) (*CheckBalanceResponse, error)
	Reduction(ctx context.Context, in *ReductionRequest, opts ...grpc.CallOption) (*ReductionResponse, error)
}

type accountClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountClient(cc grpc.ClientConnInterface) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) CheckBalance(ctx context.Context, in *CheckBalanceRequest, opts ...grpc.CallOption) (*CheckBalanceResponse, error) {
	out := new(CheckBalanceResponse)
	err := c.cc.Invoke(ctx, "/main.Account/CheckBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Reduction(ctx context.Context, in *ReductionRequest, opts ...grpc.CallOption) (*ReductionResponse, error) {
	out := new(ReductionResponse)
	err := c.cc.Invoke(ctx, "/main.Account/Reduction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	CheckBalance(context.Context, *CheckBalanceRequest) (*CheckBalanceResponse, error)
	Reduction(context.Context, *ReductionRequest) (*ReductionResponse, error)
}

// UnimplementedAccountServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (*UnimplementedAccountServer) CheckBalance(ctx context.Context, req *CheckBalanceRequest) (*CheckBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckBalance not implemented")
}
func (*UnimplementedAccountServer) Reduction(ctx context.Context, req *ReductionRequest) (*ReductionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reduction not implemented")
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_CheckBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).CheckBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Account/CheckBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).CheckBalance(ctx, req.(*CheckBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_Reduction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReductionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Reduction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Account/Reduction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Reduction(ctx, req.(*ReductionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckBalance",
			Handler:    _Account_CheckBalance_Handler,
		},
		{
			MethodName: "Reduction",
			Handler:    _Account_Reduction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
